### PR TITLE
[Aerial Robot Control] landing, halt command during vel acc-based mode

### PR DESCRIPTION
**Pull request by HarukiKozukapenguin**
### What is this
Debug in landing, halt command in XyControlMode =VEL_CONTROL_MODE, and ACC_CONTROL_MODE

### Detail

- set POS_CONTROL_MODE when navigator get landing, halt topic
- setTargetAcc = 0 in setTargetXyFromCurrentState

### CODE REVIEW

**Comment by tongtybj** [comment]
@HarukiKozukapenguin 

Very good!

Could you also add `setXyControlMode(POS_CONTROL_MODE);` in following parts:
- https://github.com/jsk-ros-pkg/jsk_aerial_robot/blob/6b211a201007ef4c022d2b5f7aff387b7be9882c/aerial_robot_control/src/flight_navigation.cpp#L409-L414
- https://github.com/jsk-ros-pkg/jsk_aerial_robot/blob/6b211a201007ef4c022d2b5f7aff387b7be9882c/aerial_robot_control/src/flight_navigation.cpp#L640-L643

**Comment by HarukiKozukapenguin** [comment]
I fixed.

**Comment by HarukiKozukapenguin** [comment]
I think we can solve this problem by setting  `setXyControlMode(POS_CONTROL_MODE);`  in call of `setTargetXyFromCurrentState` . so I change so.
Is there any comments of this solution?

**Comment by tongtybj** [comment]
> I think we can solve this problem by setting setXyControlMode(POS_CONTROL_MODE); in call of setTargetXyFromCurrentState .　Is there any comments of this solution?

Execellent! LGTM

**Comment by HarukiKozukapenguin** [comment]
Could you merge thjs PR to master branch?

**Review by tongtybj — APPROVED** [review]

**Comment by tongtybj** [comment]
@HarukiKozukapenguin 

Why you close this PR !?

**Comment by HarukiKozukapenguin** [comment]
Sorry.
I closed because I mistakenly thought this PR has already merged to main branch.
I found that this has not merged to main branch yet, so I reopened.

**Pull request merged**
