### PR TITLE
[Doc] Add docs

### PR DESCRIPTION
**Pull request by Li-Jinjie**
### What is this

This PR modifies some typos inside the system, and add a ./docs directory to maintain the instruction documents. The figure of workflow, which is used in documentation, is implemented through plantUML and will be generated automatically using an action in GitHub.

### To Do

add 3 figures from https://github.com/jsk-ros-pkg/jsk_aerial_robot/pull/406

- [x] add figure 1
- [x] add figure 2
- [x] add figure 3

### CODE REVIEW

**Comment by tongtybj** [comment]
I think this PR can be merge right now, but I am confused that why GitHub Action is not executed...

**Comment by Li-Jinjie** [comment]
This UML Action will not execute in each commit. On the contrary, it executes only when the commit includes change of .uml files. So I guess if you commit a revised .uml file to the master branch, or handling merging conflict in PR, which generates the change of .uml file, then the UML Action will execute.

**Comment by tongtybj** [comment]
No, I meaning all the workflows are not exectued for your latest commit. You can see the "green check" icon stopped at the yesterday commit.

**Comment by Li-Jinjie** [comment]
From the "Actions" on GitHub: This workflow is awaiting approval from a maintainer

**Review by tongtybj — APPROVED** [review]

**Comment by Li-Jinjie** [comment]
This is indeed because of my workflow addition: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Pull request closed without merging**
