### PR TITLE
[MuJoCo] enable to use mujoco simulator

### PR DESCRIPTION
**Pull request by sugikazu75**
## what is this
simulation interface for mujoco simulator.

## usage
```
cd ~/ros/jsk_aerial_robot_ws
rosdep install -y -r --from-paths src --ignore-src --rosdistro $ROS_DISTRO
catkin build
```
then,
```
roslaunch dragon bringup.launch real_machine:=false simulation:=true headless:=false mujoco:=true 
```
https://github.com/jsk-ros-pkg/jsk_aerial_robot/assets/64698144/96f39c6a-bfad-41ed-a348-003ee4740162

##  TODO
- [x] test under actuated robots which use flight controller in spinal (e.g. hydrus)
- [x] path CI test

### CODE REVIEW

**Comment by tongtybj** [comment]
@sugikazu75 

Great! I will go through the details. But can you tell me which file is the key of interface between our system and mujoco, and any instruction to install the mujoco (version, plance, etc).

**Comment by sugikazu75** [comment]
Interface of mujoco is implemented in ```aerial_robot_simulation/src/mujoco_robot_hw_sim.cpp``` ([mujoco_robot_hw_sim.cpp](https://github.com/jsk-ros-pkg/jsk_aerial_robot/pull/557/files#diff-edaa6e179b01cdc14e9ddc6ddb7900df82ced62ac8302f9a61da8ed12db48b0a))

There are some points in creating mujoco model for this implementation
- define rotor points as site and named including "rotor" ([code](https://github.com/jsk-ros-pkg/jsk_aerial_robot/pull/557/files#diff-ffbc53f5cb09d537ac6d899ceb1df55ff3e7d074f55361abf46fcd07c6481a32R45))
- define fc as site ([code](https://github.com/jsk-ros-pkg/jsk_aerial_robot/pull/557/files#diff-ffbc53f5cb09d537ac6d899ceb1df55ff3e7d074f55361abf46fcd07c6481a32R60))
- define actuators ([code](https://github.com/jsk-ros-pkg/jsk_aerial_robot/pull/557/files#diff-ffbc53f5cb09d537ac6d899ceb1df55ff3e7d074f55361abf46fcd07c6481a32R144-R165))
- define sensors named "acc", "gyro", and "mag" in "fc" ([code](https://github.com/jsk-ros-pkg/jsk_aerial_robot/pull/557/files#diff-ffbc53f5cb09d537ac6d899ceb1df55ff3e7d074f55361abf46fcd07c6481a32R167-R171))

This is executed by ```aerial_robot_simulation/src/mujoco_ros_control.cpp``` ([mujoco_ros_control](https://github.com/jsk-ros-pkg/jsk_aerial_robot/pull/557/files#diff-459905a5009b8b80acd629fbb6a332ebe9878711c9d3b48dbbc68610bd8de7f0R85-R147))

I use pre-build library and header files of mujoco 2.3.7 (latest) that is officialy provided, and they are automaticary downloaded under ```aerial_robot_simulation/build``` by ```catkin build```. ([Makefile](https://github.com/jsk-ros-pkg/jsk_aerial_robot/pull/557/files#diff-2b65e04d4636286b65ef476465c4019a498753f9bf8067e9cf7501cdb28d1774) and [CMakeLists.txt](https://github.com/jsk-ros-pkg/jsk_aerial_robot/pull/557/files#diff-9b28b15cf6403e578f6b15c5a80a23899dc618c6851ecf7ff0c7e18af386aaa9R18-R24))

**Comment by tongtybj** [comment]
I have succeeded to run Dragon in Mujoco. Great work!

I have several additional questions:
- Why there are many new .stl files in urdf/mesh?
- What is the role of [robots/dragon/urdf/mesh/convert.py](https://github.com/jsk-ros-pkg/jsk_aerial_robot/pull/557/files#diff-1910282233e7421bb80b2142756713f6822cfce387ccf10c3c3d10594da2cd90) 
- How is  [robots/dragon/urdf/dragon.xml](https://github.com/jsk-ros-pkg/jsk_aerial_robot/pull/557/files#diff-ffbc53f5cb09d537ac6d899ceb1df55ff3e7d074f55361abf46fcd07c6481a32) generated ? Can it be auto-generated by a custom_targert_command/target in Cmake?

**Comment by sugikazu75** [comment]
Mujoco can load only .stl or .obj. So I create .stl from .dae

convert.py is blender script that is used to generate .stl from .dae. But this code does not work blender>2.8.0 (default apt version for noetic is 2.8.2). 

Mujoco model of dragon is made from urdf and stl  using ```mujoco-2.3.7/bin/compile```  under ```aerial_robot_simulation/build```.  Then, I manually added options, ground plane, actuators, sensors. 
I think it is possible to generate automatically by CMake.

**Comment by tongtybj** [comment]
@sugikazu75 

> I think it is possible to generate automatically by CMake.

That would be really great if you can achieve this function. You can have a look at https://github.com/jsk-ros-pkg/jsk_aerial_robot/pull/488/files#diff-e84943551acde4bf669577c78ef9de2615800f0d106b2c35727c0599727ff0c4R57-R82, which generates the eus model from URDF in CMakeLists. 

BTW, I want to move the core of mujoco-ros bridge to  https://github.com/JSKAerialRobot/aerial_robot_3rdparty, as I claimed in the review report.  If you do not know how to do, I can undertake it. Plase let me know your consideration about this issue.

**Comment by sugikazu75** [comment]
@tongtybj 
I made conversion script (hard coded). 
Install blender and ```rosrun aerial_robot_simulation mujoco_model_generator.py``` is needed (I will do this by CMake). 
At this point, I can support ```dragon``` and ```mini_quadrotor``` because of following reasons. 

-  some .dae in ```hydrus``` package could not be converted to .stl by blender script. Was there any difference between how  meshes in ```hydrus``` and other package were created?
- There are some link with non positive definite inertia matrix. This cause error when loading mujoco model. When I fix it appropriately, ```hydrus_xi/hex_branch/xavier201811``` model could fly (but still not be commited).

Screenshot from 2023-09-17 21-34-29
Screenshot from 2023-09-17 21-35-00

**Comment by sugikazu75** [comment]
I agree moving mujoco related files to 3rdparty package. 
Are you assuming ```mujoco``` and ```mujoco-ros``` package will be created ?
I think it would be ideal if we could separate the part related to mujoco and the part related to aerial robot.

**Comment by tongtybj** [comment]
Can we make the build process more slient?
Right now there are so may message related to blender as follows:

> /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(_PyObject_FastCallDict+0x89) [0x7f1fc8129f29]
> /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(+0x17bec8) [0x7f1fc803eec8]
> /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(_PyEval_EvalFrameDefault+0x4ec3) [0x7f1fc8045303]
> /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(+0x17a803) [0x7f1fc803d803]
> /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(+0x17c2be) [0x7f1fc803f2be]
> /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(_PyEval_EvalFrameDefault+0x4ec3) [0x7f1fc8045303]
> /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(+0x17a803) [0x7f1fc803d803]
> /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(+0x17c2be) [0x7f1fc803f2be]
> /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(_PyEval_EvalFrameDefault+0x4ec3) [0x7f1fc8045303]
> /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(+0x17ba0f) [0x7f1fc803ea0f]
> /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(PyEval_EvalCodeEx+0x3e) [0x7f1fc803f4ce]
> /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(PyEval_EvalCode+0x1b) [0x7f1fc804024b]
> /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(PyRun_FileExFlags+0xb2) [0x7f1fc80116b2]

FYI: https://blender.stackexchange.com/questions/141427/is-there-any-way-to-silence-the-reporting-in-the-info-window-when-deleting-obj

**Comment by tongtybj** [comment]
@sugikazu75 

I found that following command is not support in ubuntu:xenial with ros kinetic. https://github.com/jsk-ros-pkg/jsk_aerial_robot/blob/9828fd126278812ed4e2a61af02d970a3f71b077/aerial_robot_simulation/scripts/convert.py#L51 

This cuase following error, which I think the version of blender (2.75) is too old or has some bug.
```
  File "/home/ros/aerial_robot_ws/src/aerial_robot_3rdparty/mujoco_ros_control/scripts/convert.py", line 49, in process_subdirectories
    bpy.ops.wm.collada_import(filepath=input_file)
  File "/usr/share/blender/scripts/modules/bpy/ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.wm.collada_import" error, could not be found
```

After a lot of trial and consideration, I decide to give up to convert collada to stl in kinetic distribution which is no longer used by our current active members. 

But we still need to pass CI for kinetic distribution. So I am going to add a condition processing that skips the conversion in the CMakeLists.txt for each robot.

**Comment by sugikazu75** [comment]
> But we still need to pass CI for kinetic distribution. So I am going to add a condition processing that skips the conversion in the CMakeLists.txt for each robot.

@tongtybj  I agree with you.

**Comment by sugikazu75** [comment]
I found that mujoco model include error is occuring in rostest. 
https://github.com/jsk-ros-pkg/jsk_aerial_robot/actions/runs/6562747138/job/17825420492#step:5:8831
https://github.com/jsk-ros-pkg/jsk_aerial_robot/actions/runs/6562747138/job/17825420492#step:5:8836
But it doesn't occur on real computer.

**Comment by tongtybj** [comment]
@sugikazu75 

Yes, it is absolutely wired. 
I am going to find reason with https://github.com/tongtybj/aerial_robot/commit/1bffcfbba0b362c50c025d25dd649422b8e38469

**Comment by tongtybj** [comment]
@sugikazu75 

Interesting result:
> \+ ls /home/runner/catkin_ws/src/jsk_aerial_robot/robots/mini_quadrotor/mujoco/
ls: cannot access '/home/runner/catkin_ws/src/jsk_aerial_robot/robots/mini_quadrotor/mujoco/': No such file or directory

https://github.com/tongtybj/aerial_robot/actions/runs/6605040325/job/17939813433#step:5:7544

**Comment by tongtybj** [comment]
@sugikazu75 

Can you check why https://github.com/JSKAerialRobot/aerial_robot_3rdparty/blob/master/mujoco_ros_control/scripts/mujoco_model_generator.py#L391 generates the relative path from current directory like:

`/home/runner/catkin_ws/src/jsk_aerial_robot/robots/mini_quadrotor/mujoco/../../../../aerial_robot_3rdparty/mujoco_ros_control/config/world.xml`

**Comment by tongtybj** [comment]
https://github.com/jsk-ros-pkg/jsk_aerial_robot/pull/557#issuecomment-1772035941 is solved by https://github.com/sugikazu75/jsk_aerial_robot/pull/3

**Comment by sugikazu75** [comment]
@tongtybj 
Thank you for your contribution.
I added bug fix in `mujoco_ros_control` and  confirm CI is passed in sugikazu75@46049ae5d72c480c8aaa8861b3766dcdd58fa355.

I want you to merge https://github.com/JSKAerialRobot/aerial_robot_3rdparty/pull/14 and https://github.com/JSKAerialRobot/aerial_robot_3rdparty/pull/15.

**Comment by tongtybj** [comment]
@sugikazu75 

I have merged https://github.com/JSKAerialRobot/aerial_robot_3rdparty/pull/14 and https://github.com/JSKAerialRobot/aerial_robot_3rdparty/pull/15.

**Review by tongtybj — APPROVED** [review]
LTGM

**Comment by tongtybj** [comment]
@sugikazu75 

Eventually, we succeed to merge this PR as a new milestone for our system. Thanks for your tremendous effort!

BTW, I hope you can draw a new diagram about our simulation system based on UML proposed in #565 .

**Pull request merged**
