### PR TITLE
edit: aerial_robot_simulation/CMakeLists.txt

### PR DESCRIPTION
**Pull request by Masa0u0**
Change C++ version: 11 -> 17

### CODE REVIEW

**Comment by tongtybj** [comment]
@Masa0u0  Thanks for your contribution to our repository. May I ask what kind of trouble or error occured when you build with C++11?

**Comment by Masa0u0** [comment]
@tongtybj 
I got "/usr/include/ignition/math6/gz/math/Helpers.hh:1059:28: error: ‘chrono_literals’ is not a namespace-name"

**Comment by sugikazu75** [comment]
@Masa0u0 
What kind of ubuntu and ros are you using?
Please tell me the result of `lsb_release -a` and `uname -a`.

**Comment by Masa0u0** [comment]
@tongtybj
I am using Ubuntu 20.04 LTS + ROS Noetic.
The results of the commands are:
 
$lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

$ uname -a
Linux Z6 5.15.0-88-generic #98~20.04.1-Ubuntu SMP Mon Oct 9 16:43:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Masa0u0** [comment]
@tongtybj 
And the Gazebo version is 11.
This might be critical.

$ gazebo --version
Gazebo multi-robot simulator, version 11.14.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org


Gazebo multi-robot simulator, version 11.14.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

**Comment by tongtybj** [comment]
The default version of Gazebo in Ubuntu20.04 seems to be `11.11.0`

```
$ gazebo --version
Gazebo multi-robot simulator, version 11.11.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org
```

Did you manually install gazebo from source ? If so, could you tell me the reason?

**Comment by Masa0u0** [comment]
@tongtybj 
I'm sorry, but I forgot how I installed Gazebo.
Gazebo of my version might have been installed when I installed ROS 2 with PX4: https://docs.px4.io/main/en/ros/ros2_comm.html

**Comment by tongtybj** [comment]
I see. Installation of ros2 might be the reason that changes the version of gazebo from ros1 noetic. 
BTW, are you going to use our system in ros2?

**Comment by Masa0u0** [comment]
@tongtybj 
No. I am going to use only URDFs. I use your robot models to test my own flight control system.
https://drive.google.com/file/d/1GaN12c3zV4jawtrBD0663d7atOViAelV/view?usp=drive_link

**Pull request closed without merging**
