### PR TITLE
ubuntu22.04 support

### PR DESCRIPTION
**Pull request by sugikazu75**
### What is this
This PR support this and related repositry on ubnutu22.04.

### Details
We use [ROS-O](https://github.com/ros-o/ros-o) for ROS1 on ubuntu22.04.
Rostest by github action on docker image ubuntu-22.04 is passed. 

### TODO
To run with real machine we have to support following packages
- [x] rosserial
- [x] mocap_optitrack

rosdep install error in some package is happning because they are still not supported in ROS-O. Currently, we are ignoring error in rosdep install because they are not necessary to build package `aerial_robot`

### PR list
- https://github.com/tongtybj/ublox/pull/1
- https://github.com/JSKAerialRobot/kalman_filter/pull/21
- https://github.com/JSKAerialRobot/sensor_interface/pull/19
- https://github.com/ros-drivers/mocap_optitrack/pull/87

### CODE REVIEW

**Comment by tongtybj** [comment]
Amazing!

**Comment by sugikazu75** [comment]
`roslaunch spinal bridge.launch` was successed in docker container.

**Comment by tongtybj** [comment]
Perfect!

**Comment by tongtybj** [comment]
One thing that I just realize is that `ros-one-desktop-full` might be not supported in Arch64 (for VIM4) yet.

**Comment by Li-Jinjie** [comment]
Is it possible to build the ROS Noetic from source on Ubuntu 22.04?

**Comment by sugikazu75** [comment]
> Is it possible to build the ROS Noetic from source on Ubuntu 22.04?

Yes it is possible.
Actually, ros-one-desktop-full is built on ubuntu-22.04 docker image and released.
Some packages can use the same sources as noetic, while others require patches.

**Comment by tongtybj** [comment]
@sugikazu75 Have you tried mocap with real machine?

**Comment by sugikazu75** [comment]
> @sugikazu75 Have you tried mocap with real machine?

Yes. I confirmed that it works well when I built `mocap_optitrack` from source in a docker container. 
I will check later using packages released by apt.

**Comment by tongtybj** [comment]
@sugikazu75 

For the mocap system in 0066, we have to use a modified branch developed by @Li-Jinjie : https://github.com/ros-drivers/mocap_optitrack/pull/83

So, we don't need to use the packages released by apt for now.

**Comment by sugikazu75** [comment]
I forgot that some people have to use that branch. If we use that branch, we need more patches equivalent to https://github.com/ros-drivers/mocap_optitrack/pull/87. 
BTW, if we are not using apt-released package, should I add it to rosinstall?

**Comment by tongtybj** [comment]
Yes, you are right. We have to combine https://github.com/ros-drivers/mocap_optitrack/pull/83, https://github.com/ros-drivers/mocap_optitrack/pull/84, https://github.com/ros-drivers/mocap_optitrack/pull/87 into one branch. 
And yes, we need to add  to the rosinstall list.

**Comment by sugikazu75** [comment]
I checked mocap is working on 22.04 with https://github.com/sugikazu75/mocap_optitrack/pull/1
I updated rosinstall for 22.04. And I created https://github.com/jsk-ros-pkg/jsk_aerial_robot/pull/632 for other distros.

**Review by tongtybj — APPROVED** [review]

**Comment by tongtybj** [comment]
@sugikazu75 

We have achieved a very important progress for the continuous development.

Thank you!

**Comment by sugikazu75** [comment]
This PR supports this and related repositry on ubuntu 22.04 using [ROS-O](https://github.com/ros-o).

@ For all developers 
Currently, ROS1 for ubuntu22.04 is built and released from my repositry (https://github.com/sugikazu75/ros-o-builder), which is public fork of https://github.com/v4hn/ros-o-builder. 
This CI process is executed once a week (refer to https://github.com/sugikazu75/ros-o-builder/blob/fee16e0d0b1951117d1ae0802252d44cd7dd1e18/.github/workflows/build.yaml#L7).

If you want some packages to be released, please tell me package name, github URL, and commit hash. Or directly create PR to https://github.com/sugikazu75/ros-o-builder like as https://github.com/v4hn/ros-o-builder/compare/build-for-jammy...sugikazu75:ros-o-builder:build-for-jammy .

**Comment by Li-Jinjie** [comment]
My MPC branch is also updated to support ubuntu22.04 and ROS-O: https://github.com/Li-Jinjie/jsk_aerial_robot_dev/tree/develop/MPC_tilt_mt/robots/beetle#beetle-art-omni 

Thank you for implementing this function!

**Pull request merged**
