### PR TITLE
[Common Quadrotor] support the common quadrotor platform

### PR DESCRIPTION
**Pull request by tongtybj**
### What is this 

Refactor the whole system to support common quadrotor platforms.

### CODE REVIEW

**Comment by tongtybj** [comment]
@Takuzumi240 

Please use this as the base for common quadrotors

**Comment by sugikazu75** [comment]
@tongtybj 
I think we should merge these commits to master for new quadrotor users. I resolved conflits and fixed a little in [this branch](https://github.com/sugikazu75/jsk_aerial_robot/tree/develop/mini_quadrotor_).
 Can you condsider merging?  or are there any tasks  remained?

**Comment by tongtybj** [comment]
@sugikazu75 

Thank you for your reminder. I will refactor all commits before merging, since there are some unnecessary conflicts with master branch.

**Comment by tongtybj** [comment]
Mini Quadrotor:

Screenshot from 2023-09-12 17-04-10

**Comment by tongtybj** [comment]
@sugikazu75 

I manually merged  https://github.com/sugikazu75/jsk_aerial_robot/commit/7930401a664d27c6ccc2485af0348332e9524950 and https://github.com/sugikazu75/jsk_aerial_robot/commit/7930401a664d27c6ccc2485af0348332e9524950 .

**Comment by tongtybj** [comment]
@sugikazu75 Please also review this PR.

**Comment by sugikazu75** [comment]
@tongtybj 
config file in hydrus package is used [here](https://github.com/jsk-ros-pkg/jsk_aerial_robot/pull/546/files#diff-757c39b61fbdc4a11bb898915f4e3da591c4d05ef00953b41427bd84128eebb5R23).
So I think mini_quadrotor package should depend on ```hydrus``` or place the same file in this package.

**Comment by sugikazu75** [comment]
LGTM

**Pull request merged**
