### PR TITLE
[Mocap][Multicast] solve the mocap disconnection problem becuase of  IGMP protocol

### PR DESCRIPTION
**Pull request by tongtybj**
### What is this

Force to send a IGMP report (respnse) message from client (e.g., robot, pc) to router to keep the connection for multicast.

### Details

- `send _import_report.py` sends the IGMP report message. However, we need to execute this script with root permission becuase of the usage of the raw socket API. Therefore the command without root permission (e.g., `rosrun`) requires password every time, which makes the operation not elegant.
- `install_igmp_report.sh`: that's why I create this file to install the above python file in `crontab` under root, which allows the system to run the python file periodicaly (i.e., every two min).

### Usage:

Just run following command once in your pc or robot that needs mocap data.
```bash
$ rosrun aerial_robot_base install_igmp_report.sh
```

### TODO:

- [ ] create a document to sumary the development.

### CODE REVIEW

**Comment by sugihara-16** [comment]
@tongtybj 
Awesome!
Are there some resources you referred to accomplish this work? If so, I would appreciate it if you share them.

**Comment by tongtybj** [comment]
The introduction of multicast and IGMP(V2):
- https://www.infraexpert.com/study/multicastz10.html
- https://daimaru-tech-blog.com/?p=349

The tool to monitor packet traffic: `wireshark`: https://www.wireshark.org/download.html

The draft of scripts are generated by chatgpt:
- Prompt1: `please create a python script to send the IGMP membership report`
- Prompt2: `please tell me a way to use crontab to run the above script every two minutes`

**Comment by sugihara-16** [comment]
Thank you so much!

**Comment by Li-Jinjie** [comment]
It's great that the commits in this PR were squashed into a single commit in the master branch, which makes it much easier for me to cherry-pick!

**Pull request merged**
